// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')
describe('Index', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    try{
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  }catch(err){
    done(err)
  }
})
  afterEach(async function() {
    try{
    await driver.quit();
  }catch(err){
    done(err)
  }
})
  it('Index', async function() {
    try{
    await driver.get("http://localhost:3000/")
    await driver.setRect(1251, 722)
    await driver.findElement(By.linkText("ScrumHelper")).click()
    await driver.findElement(By.linkText("Sign In")).click()
    await driver.findElement(By.id("username")).sendKeys("coucou")
    await driver.findElement(By.id("password")).sendKeys("h")
    await driver.findElement(By.id("password")).sendKeys(Key.ENTER)
    await driver.findElement(By.linkText("ScrumHelper")).click()
  }catch(err){
    done(err)
  }
})
})
