// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('006_addTaskThenModifyTaskThennDeleteTask', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('006_addTaskThenModifyTaskThennDeleteTask', async function() {
    await driver.get("http://localhost:3000/")
    await driver.setRect(1251, 728)
    await driver.findElement(By.linkText("Sign In")).click()
    await driver.findElement(By.id("username")).sendKeys("Test")
    await driver.findElement(By.id("password")).sendKeys("test")
    await driver.findElement(By.id("password")).sendKeys(Key.ENTER)
    await driver.findElement(By.linkText("Details")).click()
    await driver.findElement(By.linkText("Tasks")).click()
    await driver.findElement(By.linkText("Add new task")).click()
    await driver.findElement(By.id("taskName")).click()
    await driver.findElement(By.id("taskName")).sendKeys("T1")
    await driver.findElement(By.id("taskDescription")).click()
    await driver.findElement(By.id("taskDescription")).sendKeys("Ceci est une task")
    await driver.findElement(By.id("taskState1")).click()
    await driver.findElement(By.id("startDate")).click()
    await driver.findElement(By.id("startDate")).sendKeys("2019-11-29")
    await driver.findElement(By.id("taskDuration")).click()
    await driver.findElement(By.id("taskDuration")).sendKeys("1")
    await driver.findElement(By.id("taskDuration")).click()
    await driver.findElement(By.id("taskDuration")).sendKeys("0")
    await driver.findElement(By.id("taskDoD")).click()
    await driver.findElement(By.id("taskDuration")).sendKeys("-1")
    await driver.findElement(By.id("taskDuration")).click()
    await driver.findElement(By.id("taskDuration")).sendKeys("0")
    await driver.findElement(By.id("taskDuration")).click()
    await driver.findElement(By.id("taskDuration")).sendKeys("1")
    await driver.findElement(By.id("taskDuration")).click()
    {
      const element = await driver.findElement(By.id("taskDuration"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("new-task")).click()
    await driver.findElement(By.id("taskDoD")).click()
    await driver.findElement(By.id("taskDoD")).sendKeys("Ca marche")
    {
      const dropdown = await driver.findElement(By.id("taskMember"))
      await dropdown.findElement(By.xpath("//option[. = 'Test']")).click()
    }
    await driver.findElement(By.id("taskRequired")).click()
    {
      const dropdown = await driver.findElement(By.id("taskIssue"))
      await dropdown.findElement(By.xpath("//option[. = 'I1']")).click()
    }
    await driver.findElement(By.css(".btn-primary")).click()
    await driver.findElement(By.linkText("Add new task")).click()
    await driver.findElement(By.id("taskName")).click()
    await driver.findElement(By.id("taskName")).sendKeys("T2")
    await driver.findElement(By.id("taskDoD")).click()
    await driver.findElement(By.id("taskDoD")).sendKeys("Ceci est une task sans description")
    await driver.findElement(By.id("taskState2")).click()
    await driver.findElement(By.id("startDate")).click()
    await driver.findElement(By.id("startDate")).sendKeys("2019-11-22")
    await driver.findElement(By.id("taskDuration")).sendKeys("1")
    await driver.findElement(By.id("taskDuration")).click()
    {
      const dropdown = await driver.findElement(By.id("taskMember"))
      await dropdown.findElement(By.xpath("//option[. = 'Test']")).click()
    }
    {
      const dropdown = await driver.findElement(By.id("taskRequired"))
      await dropdown.findElement(By.xpath("//option[. = 'T1']")).click()
    }
    {
      const dropdown = await driver.findElement(By.id("taskIssue"))
      await dropdown.findElement(By.xpath("//option[. = 'I1']")).click()
    }
    {
      const dropdown = await driver.findElement(By.id("taskIssue"))
      await dropdown.findElement(By.xpath("//option[. = 'I3']")).click()
    }
    await driver.findElement(By.css(".btn-primary")).click()
    await driver.findElement(By.linkText("Add new task")).click()
    await driver.findElement(By.id("taskName")).click()
    await driver.findElement(By.id("taskName")).sendKeys("T3")
    await driver.findElement(By.id("taskDescription")).click()
    await driver.findElement(By.id("taskDescription")).sendKeys("Ceci est une task sans DoD")
    await driver.findElement(By.css(".form-check:nth-child(5)")).click()
    await driver.findElement(By.id("taskState3")).click()
    await driver.findElement(By.id("startDate")).click()
    await driver.findElement(By.id("startDate")).sendKeys("2019-11-30")
    await driver.findElement(By.id("taskDuration")).sendKeys("1")
    await driver.findElement(By.id("taskDuration")).click()
    await driver.findElement(By.id("taskDuration")).sendKeys("2")
    await driver.findElement(By.id("taskDuration")).click()
    {
      const element = await driver.findElement(By.id("taskDuration"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("taskDuration")).sendKeys("3")
    await driver.findElement(By.id("taskDuration")).click()
    await driver.findElement(By.id("startDate")).click()
    await driver.findElement(By.id("startDate")).sendKeys("2019-11-07")
    {
      const dropdown = await driver.findElement(By.id("taskMember"))
      await dropdown.findElement(By.xpath("//option[. = 'user1']")).click()
    }
    {
      const dropdown = await driver.findElement(By.id("taskIssue"))
      await dropdown.findElement(By.xpath("//option[. = 'I3']")).click()
    }
    await driver.findElement(By.css(".btn-primary")).click()
    await driver.findElement(By.css("#tasks_todo .mb-1")).click()
    await driver.findElement(By.linkText("Modify")).click()
    await driver.findElement(By.id("taskDescription")).click()
    await driver.findElement(By.id("taskDescription")).sendKeys("Ceci est une task modifée")
    await driver.findElement(By.id("taskName")).click()
    await driver.findElement(By.id("taskName")).sendKeys("T1 - bis")
    await driver.findElement(By.id("taskState2")).click()
    await driver.findElement(By.id("startDate")).click()
    await driver.findElement(By.id("startDate")).sendKeys("2019-11-15")
    await driver.findElement(By.id("taskDoD")).click()
    await driver.findElement(By.id("taskDuration")).sendKeys("2")
    await driver.findElement(By.id("taskDuration")).click()
    await driver.findElement(By.id("taskDuration")).sendKeys("3")
    await driver.findElement(By.id("taskDuration")).click()
    {
      const element = await driver.findElement(By.id("taskDuration"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("taskDuration")).sendKeys("4")
    await driver.findElement(By.id("taskDuration")).click()
    await driver.findElement(By.id("taskDuration")).sendKeys("5")
    await driver.findElement(By.id("taskDuration")).click()
    {
      const element = await driver.findElement(By.id("taskDuration"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("taskDoD")).sendKeys("Ca marche ???")
    await driver.findElement(By.css(".btn-primary")).click()
    await driver.findElement(By.css("#tasks_doing > .list-group-item:nth-child(2) > .mb-1")).click()
    await driver.findElement(By.linkText("Modify")).click()
    {
      const dropdown = await driver.findElement(By.id("taskRequired"))
      await dropdown.findElement(By.xpath("//option[. = 'T1 - bis']")).click()
    }
    {
      const element = await driver.findElement(By.css("#taskRequired > option:nth-child(1)"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    {
      const dropdown = await driver.findElement(By.id("taskRequired"))
      await dropdown.findElement(By.xpath("//option[. = 'T2']")).click()
    }
    {
      const dropdown = await driver.findElement(By.id("taskIssue"))
      await dropdown.findElement(By.xpath("//option[. = 'I1']")).click()
    }
    {
      const dropdown = await driver.findElement(By.id("taskIssue"))
      await dropdown.findElement(By.xpath("//option[. = 'I3']")).click()
    }
    {
      const dropdown = await driver.findElement(By.id("taskMember"))
      await dropdown.findElement(By.xpath("//option[. = 'user1']")).click()
    }
    await driver.findElement(By.css(".btn-primary")).click()
    await driver.findElement(By.css("#tasks_doing > .list-group-item:nth-child(2) > .mb-1")).click()
    await driver.findElement(By.linkText("Modify")).click()
    await driver.findElement(By.css(".form-check:nth-child(5) > .form-check-label")).click()
    await driver.findElement(By.id("startDate")).click()
    await driver.findElement(By.id("startDate")).sendKeys("2019-11-01")
    await driver.findElement(By.id("taskDoD")).click()
    await driver.findElement(By.id("taskDoD")).sendKeys("Ca marche ??? yes")
    await driver.findElement(By.css(".btn-primary")).click()
    await driver.findElement(By.css(".list-group-item:nth-child(4)")).click()
    {
      const element = await driver.findElement(By.css(".list-group-item:nth-child(4)"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css("#modalInfos65 form > .btn")).click()
    assert(await driver.switchTo().alert().getText() == "Voulez-vous vraiment supprimer cette tâche ?")
    await driver.switchTo().alert().accept()
    await driver.findElement(By.css(".btn-outline-danger")).click()
    await driver.close()
  })
})
