// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('çamarche?', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('çamarche?', async function() {
    await driver.get("http://localhost:3000/")
    await driver.findElement(By.linkText("Sign Up")).click()
    await driver.findElement(By.id("username")).sendKeys("Test2")
    await driver.findElement(By.id("password")).sendKeys("test2")
    await driver.findElement(By.id("confirmedPassword")).click()
    await driver.findElement(By.id("confirmedPassword")).sendKeys("test2")
    await driver.findElement(By.css(".btn-primary")).click()
    await driver.findElement(By.id("username")).sendKeys("Test2")
    await driver.findElement(By.id("password")).sendKeys("test2")
    await driver.findElement(By.id("password")).sendKeys(Key.ENTER)
    await driver.findElement(By.name("signout")).click()
  })
})
