language: node_js
node_js:
  - 7

dist: xenial

services:
  - xvfb

addons:
  firefox: "70.0.0"

install:
  - npm install selenium-webdriver@^3.4.0
  - npm install geckodriver
  - npm install

script:
- "npm test"
