language: node_js
node_js:
  - 7

dist: xenial

services:
  - xvfb

addons:
  firefox: "70.0.0"

before_script:
  - docker-compose up -d --build
  - chmod 777 wait-for-it.sh
  - ./wait-for-it.sh mysql:3307 -t 300

script:
- "npm test"
