language: node_js
node_js:
  - 7
addons:
  firefox: "52.0.1"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start || echo \"Unable to start virtual display.\""
  - sleep 3 # give xvfb some time to start

  - wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.15.1-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
install:
  - npm install selenium-webdriver@^3.0.0
  - npm install
  cache:
  directories:
    - node_modules
    - ~/.selenium-assistant
script:
  - npm run test

script:
- "npm test"
