language: node_js
node_js:
  - 7

dist: xenial

services:
  - xvfb

addons:
  firefox: "70.0.0"

before_script:
  - docker-compose up -d --build
  - ./wait-for-it.sh mysql:3306 -t 60

script:
- "npm test"
