language: node_js
node_js:
  - 7

dist: xenial

services:
  - xvfb

addons:
  firefox: "70.0.0"

before_script:
  - docker-compose build
  - docker-compose up -d
  - travis_wait sleep 60

script:
- "npm test"
